version: '3'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    ports:
      - 8000:80
    volumes:
      - ${APP_DIR:?err}/filebrowser/filebrowser.db:/database/filebrowser.db
      - ${APP_DIR:?err}/filebrowser/settings.json:/config/settings.json
      - ${APP_DIR}:/mnt
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser.entryPoints: https
      traefik.http.routers.filebrowser.middlewares: auth@file
    environment:
      TZ: ${TZ:?err}
      PGID: ${PGID:?err}
      PUID: ${PUID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true