version: '3'

services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
      - 8002:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true


volumes:
  portainer_data: